title: about jenn
description: This internship has provided me with a unique opportunity to delve into the dynamic landscape of data librarianship and engage with a vibrant community of professionals.
theme: jekyll-theme-cayman
